const MODELS_DATA = {
  "text": [
    { "id": "gpt-5.6-sol",                 "label": "GPT-5.6 Sol",       "editeur": "openai",    "inputPer1M": 5,     "outputPer1M": 30,  "description": "Modèle frontière d'OpenAI pour le travail professionnel complexe (contexte 1M)." },
    { "id": "gpt-5.6-terra",               "label": "GPT-5.6 Terra",     "editeur": "openai",    "inputPer1M": 2.5,   "outputPer1M": 15,  "description": "GPT-5.6 équilibré entre intelligence et coût." },
    { "id": "gpt-5.6-luna",                "label": "GPT-5.6 Luna",      "editeur": "openai",    "inputPer1M": 1,     "outputPer1M": 6,   "description": "GPT-5.6 optimisé pour les usages sensibles au coût." },
    { "id": "gpt-5.5-2026-04-23",          "label": "GPT-5.5",           "editeur": "openai",    "inputPer1M": 5,     "outputPer1M": 30,  "description": "Dernière génération OpenAI, performances de pointe en raisonnement et créativité." },
    { "id": "gpt-5.4-2026-03-05",          "label": "GPT-5.4",           "editeur": "openai",    "inputPer1M": 2.5,   "outputPer1M": 15,  "description": "Dernière génération OpenAI, performances de pointe en raisonnement et créativité." },
    { "id": "gpt-5.2-2025-12-11",          "label": "GPT-5.2",           "editeur": "openai",    "inputPer1M": 1.75,  "outputPer1M": 14, "description": "Modèle avancé avec raisonnement amélioré et large fenêtre de contexte." },
    { "id": "gpt-4.1-2025-04-14",         "label": "GPT-4.1",            "editeur": "openai",    "inputPer1M": 2,     "outputPer1M": 8,  "description": "Modèle phare d'OpenAI, excellent en codage et suivi d'instructions complexes." },
    { "id": "gpt-5.4-mini-2026-03-17",     "label": "GPT-5.4 Mini",      "editeur": "openai",    "inputPer1M": 0.75,  "outputPer1M": 4.5,"description": "Modèle mini le plus puissant d'OpenAI, excellent pour codage, usage d'outils et sous-agents." },
    { "id": "gpt-5.4-nano-2026-03-17",     "label": "GPT-5.4 Nano",      "editeur": "openai",    "inputPer1M": 0.2,   "outputPer1M": 1.25,"description": "Version ultra-rapide et économique de GPT-5.4, idéale pour classification, extraction et sous-agents." },
    { "id": "claude-fable-5",              "label": "Claude Fable 5",    "editeur": "anthropic", "inputPer1M": 10,    "outputPer1M": 50, "description": "Nouvelle classe d'intelligence d'Anthropic (Claude 5), pensée pour les agents de longue durée et les tâches les plus complexes." },
    { "id": "claude-opus-4-8",             "label": "Claude Opus 4.8",   "editeur": "anthropic", "inputPer1M": 5,     "outputPer1M": 25, "description": "Pour le codage agentique complexe et le travail en entreprise." },
    { "id": "claude-sonnet-5",             "label": "Claude Sonnet 5",   "editeur": "anthropic", "inputPer1M": 3,     "outputPer1M": 15, "description": "La meilleure combinaison vitesse / intelligence d'Anthropic." },
    { "id": "claude-opus-4-7",             "label": "Claude Opus 4.7",   "editeur": "anthropic", "inputPer1M": 5,     "outputPer1M": 25, "description": "Modèle le plus puissant d'Anthropic, excelle en analyse approfondie et tâches complexes." },
    { "id": "claude-opus-4-6",             "label": "Claude Opus 4.6",   "editeur": "anthropic", "inputPer1M": 5,     "outputPer1M": 25, "description": "Version antérieure du modèle le plus puissant d'Anthropic, excelle en analyse approfondie et tâches complexes." },
    { "id": "claude-sonnet-4-5-20250929",  "label": "Claude Sonnet 4.5", "editeur": "anthropic", "inputPer1M": 3,     "outputPer1M": 15, "description": "Équilibre optimal entre performance et coût, très bon en rédaction et codage." },
    { "id": "claude-haiku-4-5-20251001",   "label": "Claude Haiku 4.5",  "editeur": "anthropic", "inputPer1M": 1,     "outputPer1M": 5,  "description": "Modèle rapide et abordable, parfait pour les réponses courtes et le traitement en masse." },
    { "id": "gemini-3.5-flash",            "label": "Gemini 3.5 Flash",  "editeur": "google",    "inputPer1M": 1.5,   "outputPer1M": 9,  "description": "Le modèle le plus intelligent de Google, performances de pointe en codage et tâches agentiques." },
    { "id": "gemini-3.1-pro-preview",      "label": "Gemini 3.1 Pro",    "editeur": "google",    "inputPer1M": 2,     "outputPer1M": 12, "description": "Dernier modèle Pro de Google, performant en raisonnement multimodal et long contexte." },
    { "id": "gemini-3-flash-preview",      "label": "Gemini 3 Flash",    "editeur": "google",    "inputPer1M": 0.5,   "outputPer1M": 3.0, "description": "Dernier modèle FLash, combinant rapidité et une intelligence de pointe." },
    { "id": "gemini-3.1-flash-lite",       "label": "Gemini 3.1 Flash Lite",  "editeur": "google",    "inputPer1M": 0.25,  "outputPer1M": 1.5, "description": "Modèle ultra-rapide et économique de Google, bon rapport qualité-prix." },
    { "id": "gemma-4-31b-it",             "label": "Gemma 4 (31b)",      "editeur": "google",   "inputPer1M": 0,      "outputPer1M": 0,"description": "Le modèle dense de Google, conçu pour une qualité maximale à un prix dérisoire. Temporairement gratuit." },
    { "id": "mistral-medium-3-5",         "label": "Mistral Medium 3.5", "editeur": "mistral",   "inputPer1M": 1.5,   "outputPer1M": 7.5,"description": "Le modèle multimodal de pointe avec raisonnement. Actuellement le modèle le plus performant de Mistral." },
    { "id": "mistral-large-latest",        "label": "Mistral Large 3",   "editeur": "mistral",   "inputPer1M": 0.5,   "outputPer1M": 1.5,  "description": "Le modèle phare et le performant de Mistral. Cocorico." },
    { "id": "mistral-small-latest",        "label": "Mistral Small 4",   "editeur": "mistral",   "inputPer1M": 0.15,  "outputPer1M": 0.6,"description": "Petit modèle économique, très rapide, avec raisonnement, parfait pour les tâches simples." },
    { "id": "ministral-8b-latest",         "label": "Ministral 8B",      "editeur": "mistral",   "inputPer1M": 0.15,  "outputPer1M": 0.15,"description": "Modèle compact (8B) optimisé pour la rapidité d'exécution et l'edge computing." },
    { "id": "deepseek-chat",               "label": "DeepSeek V3.2",     "editeur": "deepseek",  "inputPer1M": 0.14,  "outputPer1M": 0.28, "description": "Modèle phare de DeepSeek, excellent rapport qualité-prix en codage et raisonnement (mode raisonnement activable)." },
    { "id": "deepseek-v4-pro",             "label": "DeepSeek V4 Pro",   "editeur": "deepseek",  "inputPer1M": 1.74,  "outputPer1M": 3.48, "description": "Dernier modèle de DeepSeek." },
    { "id": "deepseek-v4-flash",           "label": "DeepSeek V4 Flash", "editeur": "deepseek",  "inputPer1M": 0.14,  "outputPer1M": 0.28, "description": "Dernier modèle de DeepSeek." },
    { "id": "grok-4.5",                    "label": "Grok 4.5",         "editeur": "grok",       "inputPer1M": 2,     "outputPer1M": 6,    "description": "Dernier modèle phare de xAI : codage, faible taux d'hallucination et usage d'outils agentique (contexte 500K)." },
    { "id": "grok-4.3",                    "label": "Grok 4.3",         "editeur": "grok",       "inputPer1M": 1.25,  "outputPer1M": 2.50, "description": "Modèle phare de xAI, très performant en analyse." },
    { "id": "grok-4.20-0309-reasoning",    "label": "Grok 4.20",         "editeur": "grok",      "inputPer1M": 2,     "outputPer1M": 6,    "description": "Modèle phare de xAI, très performant en analyse." },
    { "id": "grok-4-1-fast-reasoning",     "label": "Grok 4.1 Fast",     "editeur": "grok",      "inputPer1M": 0.2,   "outputPer1M": 0.5,  "description": "Modèle rapide et économique de xAI, fenêtre de contexte de 2M tokens." },
    { "id": "glm-5.2",                     "label": "GLM-5.2",           "editeur": "zai",       "inputPer1M": 1.4,   "outputPer1M": 4.4,  "description": "Dernier modèle phare de Zhipu AI, excellent en codage sur les tâches longues (mode raisonnement activable)." },
    { "id": "glm-5-turbo",                 "label": "GLM-5 Turbo",       "editeur": "zai",       "inputPer1M": 1.2,   "outputPer1M": 4.0,  "description": "Version rapide de GLM-5, bon compromis performance / latence (mode raisonnement activable)." },
    { "id": "glm-5.1",                     "label": "GLM-5.1",           "editeur": "zai",       "inputPer1M": 1.4,   "outputPer1M": 4.4,  "description": "Modèle codage le plus puissant de Zhipu AI, 200K de contexte, avec mode raisonnement activable." },
    { "id": "glm-5",                       "label": "GLM-5",             "editeur": "zai",       "inputPer1M": 1,     "outputPer1M": 3.2,  "description": "Modèle phare de Zhipu AI (744B MoE), rival des meilleurs modèles mondiaux (mode raisonnement activable)." },
    { "id": "glm-4.7-flash",               "label": "GLM-4.7 Flash",     "editeur": "zai",       "inputPer1M": 0,     "outputPer1M": 0,    "description": "Modèle ultra-rapide de Zhipu, gratuit, bon pour les tâches simples." }
  ],
  "image": [
    { "id": "gemini-3-pro-image",            "label": "Nano Banana Pro", "editeur": "google", "inputPer1M": 2,   "outputPer1M": 12, "imageOutput": 0.134, "imagePricing": { "1K": 0.134, "2K": 0.134, "4K": 0.24 }, "description": "Génération d'images via Gemini Pro, haute qualité et bonne compréhension des prompts." },
    { "id": "gemini-3.1-flash-image",        "label": "Nano Banana 2",  "editeur": "google", "inputPer1M": 0.5, "outputPer1M": 3,  "imageOutput": 0.067, "imagePricing": { "1K": 0.067, "2K": 0.101, "4K": 0.151 }, "description": "Génération d'images rapide et économique basée sur Gemini Flash." },
    { "id": "gemini-3.1-flash-lite-image",   "label": "Nano Banana 2 Lite", "editeur": "google", "inputPer1M": 0.25, "outputPer1M": 1.5, "imageOutput": 0.0336, "imagePricing": { "1K": 0.0336 }, "description": "Génération et retouche d'images à très faible latence, la moins chère de Google (résolution 1K)." },
    { "id": "gpt-image-2",                   "label": "GPT Image 2",    "editeur": "openai",     "inputPer1M": 5,   "outputPer1M": 0,  "imageOutput": 0.211, "imagePricing": { "low": { "1024x1024": 0.006, "1024x1536": 0.005, "1536x1024": 0.005 }, "medium": { "1024x1024": 0.053, "1024x1536": 0.041, "1536x1024": 0.041 }, "high": { "1024x1024": 0.211, "1024x1536": 0.165, "1536x1024": 0.165 } }, "description": "Dernière génération GPT Image d'OpenAI, fidélité supérieure et support de résolutions libres." },
    { "id": "gpt-image-1.5",                 "label": "GPT Image 1.5",  "editeur": "openai",     "inputPer1M": 5,   "outputPer1M": 10, "imageOutput": 0.133, "imagePricing": { "low": { "1024x1024": 0.009, "1024x1536": 0.013, "1536x1024": 0.013 }, "medium": { "1024x1024": 0.034, "1024x1536": 0.05, "1536x1024": 0.05 }, "high": { "1024x1024": 0.133, "1024x1536": 0.2, "1536x1024": 0.2 } }, "description": "Modèle de génération d'images d'OpenAI, excellent en réalisme et créativité." },
    { "id": "gpt-image-1-mini",              "label": "GPT Image 1 Mini", "editeur": "openai",   "inputPer1M": 2,   "outputPer1M": 0,  "imageOutput": 0.036, "imagePricing": { "low": { "1024x1024": 0.005, "1024x1536": 0.006, "1536x1024": 0.006 }, "medium": { "1024x1024": 0.011, "1024x1536": 0.015, "1536x1024": 0.015 }, "high": { "1024x1024": 0.036, "1024x1536": 0.052, "1536x1024": 0.052 } }, "description": "Version mini de GPT Image, nettement moins chère, idéale pour les itérations rapides." }
  ],
  "search": [
    { "id": "sonar",                "label": "Sonar",               "editeur": "perplexity", "inputPer1M": 1, "outputPer1M": 1, "description": "Recherche web avec synthèse de sources multiples et citations. 5$/1k recherches web" },
    { "id": "sonar-pro",            "label": "Sonar Pro",            "editeur": "perplexity", "inputPer1M": 3, "outputPer1M": 15, "description": "Recherche web avancée avec synthèse de sources multiples et citations. 5$/1k recherches web" },
    { "id": "sonar-reasoning-pro",  "label": "Sonar Reasoning Pro",  "editeur": "perplexity", "inputPer1M": 2, "outputPer1M": 8,  "description": "⚠️ Très coûteux. Recherche web avec raisonnement approfondi pour les questions complexes. 5$/1k recherches web" }
  ],
  "tts": [
    { "id": "gpt-4o-mini-tts",                  "label": "OpenAI (gpt-4o-mini-tts)",          "editeur": "openai",  "prix": "$12/1M car.",  "description": "Synthèse vocale rapide et expressive d'OpenAI." },
    { "id": "gemini-3.1-flash-tts-preview",      "label": "Google (Gemini 3.1 Flash TTS)",     "editeur": "google",  "prix": "$1 / $20",      "description": "Dernière génération TTS de Google — 70+ langues, dialogue multi-voix, contrôle expressif via tags audio." },
    { "id": "gemini-2.5-flash-preview-tts",      "label": "Google (Gemini 2.5 Flash TTS)",     "editeur": "google",  "prix": "$0.50 / $10",   "description": "Synthèse vocale de Google via Gemini, voix naturelles multilingues." },
    { "id": "voxtral-mini-tts-2603",             "label": "Mistral (Voxtral Mini TTS)",        "editeur": "mistral", "prix": "$16/1M car.", "description": "Synthèse vocale légère et rapide par Mistral." },
    { "id": "system-tts",                        "label": "Système (navigateur)",              "editeur": "system",  "prix": "Gratuit",       "description": "Synthèse vocale native du navigateur (voix du système)." }
  ],
  "stt": [
    { "id": "whisper-1",              "label": "OpenAI (Whisper)",           "editeur": "openai",  "prix": "$0.006/min",  "description": "Transcription audio précise et multilingue par OpenAI." },
    { "id": "gemini-3.1-flash-lite", "label": "Google (Gemini 3.1 Flash Lite)", "editeur": "google",  "prix": "$0.50 / $1.5",  "description": "Transcription audio via Gemini Flash Lite, rapide et polyvalent." },
    { "id": "voxtral-mini-latest",    "label": "Mistral (Voxtral Mini 2)",  "editeur": "mistral", "prix": "$0.003/min",  "description": "Modèle de transcription de pointe par Mistral, léger et rapide." }
  ]
};
